MyLang ::= expression

expression ::= term,expression2
expression2 ::= "+",term,expression2 
expression2 ::= ""
term ::= term2,term3
term2 ::= factor,operation
term3 ::= "*", term, term3
term3 ::= ""
operation ::= "~",factor,operation
operation ::= ""

term2 ::= "*",factor,term2
term2 ::= term3
term2 ::= ""
term3 ::= "~",factor,term3
term3 ::= ""
factor ::= "("expression")"
factor ::= integer
factor ::= binary
factor ::= hexa
factor ::= array
factor ::= rand

digits ::={"0","1","2","3","4","5","6","7","8","9"}
integer ::= digits+
binary ::= "b",("0"|"1")+
hexa ::= "0x",hexdigits+
hexdigits ::= {"0","1","2","3","4","5","6","7","8","9","a","b","c","d","e","f","A","B","C","D","E","F"}
array ::= "[",arrayNumbers,"]"
arrayNumbers ::= integerArray
arrayNumbers ::= binaryArray
arrayNumbers ::= hexaArray
integerArray ::= integer
integerArray ::= integerArray,separator,integer
binaryArray ::= binary
binaryArray ::= binaryArray,separator,binary
hexaArray ::= hexa
hexaArray ::= hexaArray,separator,hexa
separator = ","

rand ::= "rand(",rand_arguments,")"
rand_arguments ::= ""
rand_arguments ::= data_type
rand_arguments ::= integer,separator,integer
rand_arguments ::= integer,separator,integer,separator,data_type
rand_arguments ::= integer
rand_arguments ::= integer,separator,data_type
rand_arguments ::= integer,separator,integer,separator,integer
rand_arguments ::= integer,separator,integer,separator,integer,separator,data_type

data_type ::= "int"
data_type ::= "bin"
data_type ::= "hex"
